# This file was generated by GoReleaser. DO NOT EDIT.
class GittyUp < Formula
  desc ""
  homepage ""
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/liatrio/gitty-up/releases/download/v0.0.5/gitty-up_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "0299f34e9d92122b79fb81eef3ecb3473b55c88efb6b2ba3b85961bc2e1f8253"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/liatrio/gitty-up/releases/download/v0.0.5/gitty-up_0.0.5_Linux_x86_64.tar.gz"
      sha256 "f52ce4c9c8df204939fa5f9b106e2eecade409effaefa5e4987a28668b3874a6"
    end
  end

  def install
    bin.install "gitty-up"
  end
end
