# This file was generated by GoReleaser. DO NOT EDIT.
class GittyUp < Formula
  desc ""
  homepage ""
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/liatrio/gitty-up/releases/download/v0.0.7/gitty-up_0.0.7_Darwin_x86_64.tar.gz"
    sha256 "8d3fc858cc9127443657d6d142b71c0a00ee662113ba8b3e5f2a269fc61fdf66"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/liatrio/gitty-up/releases/download/v0.0.7/gitty-up_0.0.7_Linux_x86_64.tar.gz"
      sha256 "00506ab273082c3874da553ba9b12d55e749b5df5c461705ec104841238a2baf"
    end
  end

  def install
    bin.install "gitty-up"
  end
end
